version: '3.4'

services:
  misa.moviestore:
    container_name: misa.moviestore
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5103:80"
    depends_on:
      - misa.data
  misa.data:
    container_name: misa.data
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
