version: '3.5'

services:
  misa.moviestore:
    image: ${DOCKER_REGISTRY-}misamoviestore
    build:
      context: .
      dockerfile: Dockerfile
  misa.data:
    image: microsoft/mssql-server-linux:2017-latest